### ISSUE TITLE
Earth totaly black

### ISSUE THREAD

**Issue by Pheonor** [gaeaplus/gaeaplus#6] opened 2013-08-29 22:05 UTC
Hi,

When I start the example application, I could only use the default WorldWind shading, all other render to a black Earth.

![image](https://f.cloud.github.com/assets/2014432/1053783/af0a3228-10f6-11e3-9aff-42d31e86c244.png)

I got the following message into log:

30 août 2013 00:02:55 si.xlab.gaea.core.shaders.BasicGLSLCompiler printGLLog
GRAVE: OpenGL error number: 1282 description: no error
30 août 2013 00:02:55 si.xlab.gaea.core.shaders.BasicGLSLCompiler loadProgram
INFO: Compiling shader: /D:/Documents/Code/gaeaplus-master/gaeaplus-master/out/production/gaeaplus-master/si/xlab/gaea/core/shaders/data/TerrainLightingAerialPerspective_1.glsl

30 août 2013 00:02:55 si.xlab.gaea.core.shaders.BasicGLSLCompiler checkShaderLinkError
INFO: Shader validation: Validation Error: Samplers of different types point to the same texture unit
Validation Error: Samplers of different types point to the same texture unit

30 août 2013 00:02:55 si.xlab.gaea.core.shaders.BasicShaderFactory buildGLSLShader
GRAVE: Incomplete BasicShader: /D:/Documents/Code/gaeaplus-master/gaeaplus-master/out/production/gaeaplus-master/si/xlab/gaea/core/shaders/data/TerrainLightingAerialPerspective_1.glsl

30 août 2013 00:02:55 si.xlab.gaea.core.shaders.BasicGLSLCompiler checkShaderLinkError
INFO: Shader validation: Validation Error: Samplers of different types point to the same texture unit
Validation Error: Samplers of different types point to the same texture unit

30 août 2013 00:02:55 si.xlab.gaea.core.shaders.BasicShaderFactory buildGLSLShader
GRAVE: Incomplete BasicShader: /D:/Documents/Code/gaeaplus-master/gaeaplus-master/out/production/gaeaplus-master/si/xlab/gaea/core/shaders/data/Atmosphere_1.glsl

Regards

**Comment by clarejor** [comment] 2013-11-20 02:30
I have this issue as well. Anything but "Default World Wind" shading results in a totally back earth and sky. I have tested it on 3 different machines. Two with nvidia graphics cards, and one with an Intel core i7.

Nov 19, 2013 9:29:54 PM si.xlab.gaea.core.shaders.BasicGLSLCompiler loadProgram
INFO: Compiling shader: file:/C:/Documents%20and%20Settings/Jordan/My%20Documents/Downloads/gaeaplus-master/gaeaplus-master/build/jar/GaeaPlusOpenSource.jar!/si/xlab/gaea/core/shaders/data/TerrainNormal.glsl
Nov 19, 2013 9:29:54 PM si.xlab.gaea.core.shaders.BasicShaderFactory buildGLSLShader
INFO: Shader loaded: file:/C:/Documents%20and%20Settings/Jordan/My%20Documents/Downloads/gaeaplus-master/gaeaplus-master/build/jar/GaeaPlusOpenSource.jar!/si/xlab/gaea/core/shaders/data/TerrainNormal.glsl
Nov 19, 2013 9:29:54 PM si.xlab.gaea.core.shaders.BasicGLSLCompiler loadProgram
INFO: Compiling shader: file:/C:/Documents%20and%20Settings/Jordan/My%20Documents/Downloads/gaeaplus-master/gaeaplus-master/build/jar/GaeaPlusOpenSource.jar!/si/xlab/gaea/core/shaders/data/DefferedColor.glsl
Nov 19, 2013 9:29:54 PM si.xlab.gaea.core.shaders.BasicShaderFactory buildGLSLShader
INFO: Shader loaded: file:/C:/Documents%20and%20Settings/Jordan/My%20Documents/Downloads/gaeaplus-master/gaeaplus-master/build/jar/GaeaPlusOpenSource.jar!/si/xlab/gaea/core/shaders/data/DefferedColor.glsl
Nov 19, 2013 9:29:54 PM si.xlab.gaea.core.shaders.BasicGLSLShader$ParameterCache getParameter
WARNING: In shader: file:/C:/Documents%20and%20Settings/Jordan/My%20Documents/Downloads/gaeaplus-master/gaeaplus-master/build/jar/GaeaPlusOpenSource.jar!/si/xlab/gaea/core/shaders/data/DefferedColor.glsl ShaderParameter: u_drawDistance NOT FOUND or NOT USED!
Nov 19, 2013 9:29:54 PM si.xlab.gaea.core.shaders.BasicGLSLShader$ParameterCache getParameter
WARNING: In shader: file:/C:/Documents%20and%20Settings/Jordan/My%20Documents/Downloads/gaeaplus-master/gaeaplus-master/build/jar/GaeaPlusOpenSource.jar!/si/xlab/gaea/core/shaders/data/DefferedColor.glsl ShaderParameter: normalFactor NOT FOUND or NOT USED!
Nov 19, 2013 9:29:54 PM si.xlab.gaea.core.shaders.BasicGLSLCompiler loadProgram
INFO: Compiling shader: file:/C:/Documents%20and%20Settings/Jordan/My%20Documents/Downloads/gaeaplus-master/gaeaplus-master/build/jar/GaeaPlusOpenSource.jar!/si/xlab/gaea/core/shaders/data/SurfaceTileShader.glsl
Nov 19, 2013 9:29:54 PM si.xlab.gaea.core.shaders.BasicShaderFactory buildGLSLShader
INFO: Shader loaded: file:/C:/Documents%20and%20Settings/Jordan/My%20Documents/Downloads/gaeaplus-master/gaeaplus-master/build/jar/GaeaPlusOpenSource.jar!/si/xlab/gaea/core/shaders/data/SurfaceTileShader.glsl
Nov 19, 2013 9:29:54 PM si.xlab.gaea.core.shaders.BasicGLSLShader$ParameterCache getParameter
WARNING: In shader: file:/C:/Documents%20and%20Settings/Jordan/My%20Documents/Downloads/gaeaplus-master/gaeaplus-master/build/jar/GaeaPlusOpenSource.jar!/si/xlab/gaea/core/shaders/data/SurfaceTileShader.glsl ShaderParameter: exaggeration NOT FOUND or NOT USED!
Nov 19, 2013 9:29:54 PM si.xlab.gaea.core.shaders.BasicGLSLShader$ParameterCache getParameter
WARNING: In shader: file:/C:/Documents%20and%20Settings/Jordan/My%20Documents/Downloads/gaeaplus-master/gaeaplus-master/build/jar/GaeaPlusOpenSource.jar!/si/xlab/gaea/core/shaders/data/SurfaceTileShader.glsl ShaderParameter: eyeToWorld NOT FOUND or NOT USED!
Nov 19, 2013 9:29:54 PM si.xlab.gaea.core.shaders.BasicGLSLShader$ParameterCache getParameter
WARNING: In shader: file:/C:/Documents%20and%20Settings/Jordan/My%20Documents/Downloads/gaeaplus-master/gaeaplus-master/build/jar/GaeaPlusOpenSource.jar!/si/xlab/gaea/core/shaders/data/SurfaceTileShader.glsl ShaderParameter: u_drawDistance NOT FOUND or NOT USED!
Nov 19, 2013 9:29:54 PM si.xlab.gaea.core.shaders.BasicGLSLShader$ParameterCache getParameter
WARNING: In shader: file:/C:/Documents%20and%20Settings/Jordan/My%20Documents/Downloads/gaeaplus-master/gaeaplus-master/build/jar/GaeaPlusOpenSource.jar!/si/xlab/gaea/core/shaders/data/SurfaceTileShader.glsl ShaderParameter: normalFactor NOT FOUND or NOT USED!
Nov 19, 2013 9:29:54 PM si.xlab.gaea.core.shaders.BasicGLSLShader$ParameterCache getParameter
WARNING: In shader: file:/C:/Documents%20and%20Settings/Jordan/My%20Documents/Downloads/gaeaplus-master/gaeaplus-master/build/jar/GaeaPlusOpenSource.jar!/si/xlab/gaea/core/shaders/data/SurfaceTileShader.glsl ShaderParameter: texelSize NOT FOUND or NOT USED!
Nov 19, 2013 9:29:54 PM si.xlab.gaea.core.shaders.BasicGLSLShader$ParameterCache getParameter
WARNING: In shader: file:/C:/Documents%20and%20Settings/Jordan/My%20Documents/Downloads/gaeaplus-master/gaeaplus-master/build/jar/GaeaPlusOpenSource.jar!/si/xlab/gaea/core/shaders/data/SurfaceTileShader.glsl ShaderParameter: sector NOT FOUND or NOT USED!
Nov 19, 2013 9:29:54 PM si.xlab.gaea.core.shaders.BasicGLSLShader$ParameterCache getParameter
WARNING: In shader: file:/C:/Documents%20and%20Settings/Jordan/My%20Documents/Downloads/gaeaplus-master/gaeaplus-master/build/jar/GaeaPlusOpenSource.jar!/si/xlab/gaea/core/shaders/data/SurfaceTileShader.glsl ShaderParameter: texelScale NOT FOUND or NOT USED!
Nov 19, 2013 9:29:55 PM si.xlab.gaea.core.shaders.BasicGLSLCompiler printGLLog
SEVERE: OpenGL error number: 1282 description: no error
Nov 19, 2013 9:29:55 PM si.xlab.gaea.core.shaders.BasicGLSLCompiler loadProgram
INFO: Compiling shader: file:/C:/Documents%20and%20Settings/Jordan/My%20Documents/Downloads/gaeaplus-master/gaeaplus-master/build/jar/GaeaPlusOpenSource.jar!/si/xlab/gaea/core/shaders/data/TerrainLightingAerialPerspective_1.glsl
Nov 19, 2013 9:29:55 PM si.xlab.gaea.core.shaders.BasicShaderFactory buildGLSLShader
INFO: Shader loaded: file:/C:/Documents%20and%20Settings/Jordan/My%20Documents/Downloads/gaeaplus-master/gaeaplus-master/build/jar/GaeaPlusOpenSource.jar!/si/xlab/gaea/core/shaders/data/TerrainLightingAerialPerspective_1.glsl
Nov 19, 2013 9:29:55 PM si.xlab.gaea.core.shaders.BasicGLSLShader$ParameterCache getParameter
WARNING: In shader: file:/C:/Documents%20and%20Settings/Jordan/My%20Documents/Downloads/gaeaplus-master/gaeaplus-master/build/jar/GaeaPlusOpenSource.jar!/si/xlab/gaea/core/shaders/data/TerrainLightingAerialPerspective_1.glsl ShaderParameter: zNear NOT FOUND or NOT USED!
Nov 19, 2013 9:29:55 PM si.xlab.gaea.core.shaders.BasicGLSLShader$ParameterCache getParameter
WARNING: In shader: file:/C:/Documents%20and%20Settings/Jordan/My%20Documents/Downloads/gaeaplus-master/gaeaplus-master/build/jar/GaeaPlusOpenSource.jar!/si/xlab/gaea/core/shaders/data/TerrainLightingAerialPerspective_1.glsl ShaderParameter: zFar NOT FOUND or NOT USED!
Nov 19, 2013 9:29:55 PM si.xlab.gaea.core.shaders.BasicGLSLCompiler loadProgram
INFO: Compiling shader: file:/C:/Documents%20and%20Settings/Jordan/My%20Documents/Downloads/gaeaplus-master/gaeaplus-master/build/jar/GaeaPlusOpenSource.jar!/si/xlab/gaea/core/shaders/data/Atmosphere_1.glsl
Nov 19, 2013 9:29:55 PM si.xlab.gaea.core.shaders.BasicShaderFactory buildGLSLShader
INFO: Shader loaded: file:/C:/Documents%20and%20Settings/Jordan/My%20Documents/Downloads/gaeaplus-master/gaeaplus-master/build/jar/GaeaPlusOpenSource.jar!/si/xlab/gaea/core/shaders/data/Atmosphere_1.glsl

**Comment by ghost** [comment] 2013-11-20 06:27
I get similar warnings, but my video driver crashes every time I start the application. The map shows up for about 3-4 seconds, then the video driver crashes. When the video comes back, the application goes away.

NVIDIA error: The NVIDIA OpenGL driver lost connection with the display driver due to exceeding the Windows Time-Out limit and is unable to continue.

The final log from the console is:
     [java] Java Result: 1853227064

Video card is an NVIDIA Quadro FX 3700M with 1GB. Laptop has 10GB, Win7x64.

Sometimes video driver does not restart and I end up getting a BSOD. Guess this app isn't for me.

**Comment by vcucek** [comment] 2013-11-27 08:59
Hello,
I hope, that we have fixed the problem.

We found out that the generation of atmosphere effect textures fails on
certain GPUs/drivers. We have now supplied pre-calculated, known to be
valid textures with the source and disabled the generation.

If that fixes your problem, please let us know.

**Comment by ghost** [comment] 2013-11-27 14:16
The latest does not crash my video driver, but it does dump a constant stream of the following stack trace:

```
 [java] Nov 27, 2013 8:13:33 AM gov.nasa.worldwind.WorldWindowGLAutoDrawable display
 [java] SEVERE: Exception while attempting to repaint WorldWindow
 [java] java.lang.IllegalArgumentException: URI is not hierarchical
 [java]     at java.io.File.<init>(File.java:392)
 [java]     at si.xlab.gaea.core.layers.atm.Atmosphere.loadDefaultTextures(Unknown Source)
 [java]     at si.xlab.gaea.core.layers.atm.Atmosphere.precompute(Unknown Source)
 [java]     at si.xlab.gaea.core.GlobalLighting.renderEffects(Unknown Source)
 [java]     at si.xlab.gaea.core.GaeaSceneController.doRepaint(Unknown Source)
 [java]     at gov.nasa.worldwind.AbstractSceneController.repaint(Unknown Source)
 [java]     at gov.nasa.worldwind.WorldWindowGLAutoDrawable.doDisplay(Unknown Source)
 [java]     at gov.nasa.worldwind.WorldWindowGLAutoDrawable.display(Unknown Source)
 [java]     at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:373)
 [java]     at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:358)
 [java]     at javax.media.opengl.awt.GLCanvas$7.run(GLCanvas.java:983)
 [java]     at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:655)
 [java]     at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:594)
 [java]     at javax.media.opengl.awt.GLCanvas$8.run(GLCanvas.java:996)
 [java]     at javax.media.opengl.Threading.invoke(Threading.java:193)
 [java]     at javax.media.opengl.awt.GLCanvas.display(GLCanvas.java:449)
 [java]     at javax.media.opengl.awt.GLCanvas.paint(GLCanvas.java:499)
 [java]     at javax.media.opengl.awt.GLCanvas.update(GLCanvas.java:688)
 [java]     at sun.awt.RepaintArea.updateComponent(RepaintArea.java:255)
 [java]     at sun.awt.RepaintArea.paint(RepaintArea.java:232)
 [java]     ...
```

The values of the URIs are:
jar:file:/C:/working/gaeaplus-master/build/jar/GaeaPlusOpenSource.jar!/si/xlab/gaea/core/layers/atm/transmittance.dat
jar:file:/C:/working/gaeaplus-master/build/jar/GaeaPlusOpenSource.jar!/si/xlab/gaea/core/layers/atm/irradiance.dat
jar:file:/C:/working/gaeaplus-master/build/jar/GaeaPlusOpenSource.jar!/si/xlab/gaea/core/layers/atm/inscatter.dat

Modified Atmosphere class to read the resources as a stream to get rid of the above error, but now get:

```
 [java] SEVERE: Exception while attempting to repaint WorldWindow
 [java] java.lang.IndexOutOfBoundsException: Required 196608 remaining bytes in buffer, only had 90792
 [java]     at com.jogamp.common.nio.Buffers.rangeCheckBytes(Buffers.java:980)
 [java]     at jogamp.opengl.gl4.GL4bcImpl.glTexImage2D(GL4bcImpl.java:25278)
 [java]     at si.xlab.gaea.core.layers.atm.Atmosphere.loadDefaultTextures(Unknown Source)
 [java]     at si.xlab.gaea.core.layers.atm.Atmosphere.precompute(Unknown Source)
 [java]     at si.xlab.gaea.core.GlobalLighting.renderEffects(Unknown Source)
 [java]     at si.xlab.gaea.core.GaeaSceneController.doRepaint(Unknown Source)
 [java]     at gov.nasa.worldwind.AbstractSceneController.repaint(Unknown Source)
 [java]     at gov.nasa.worldwind.WorldWindowGLAutoDrawable.doDisplay(Unknown Source)
 [java]     at gov.nasa.worldwind.WorldWindowGLAutoDrawable.display(Unknown Source)
 [java]     at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:373)
 [java]     at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:358)
 [java]     at javax.media.opengl.awt.GLCanvas$7.run(GLCanvas.java:983)
 [java]     at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:655)
 [java]     at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:594)
 [java]     at javax.media.opengl.awt.GLCanvas$8.run(GLCanvas.java:996)
 [java]     at javax.media.opengl.Threading.invoke(Threading.java:193)
 [java]     at javax.media.opengl.awt.GLCanvas.display(GLCanvas.java:449)
 [java]     at javax.media.opengl.awt.GLCanvas.paint(GLCanvas.java:499)
 [java]     at javax.media.opengl.awt.GLCanvas.update(GLCanvas.java:688)
 [java]     at sun.awt.RepaintArea.updateComponent(RepaintArea.java:255)
 [java]     at sun.awt.RepaintArea.paint(RepaintArea.java:232)
 [java]     ...
```

Thank You.

**Comment by Pheonor** [comment] 2013-11-27 19:23
Hi,

still some error and a black layer.

27 nov. 2013 19:31:59 si.xlab.gaea.core.shaders.BasicGLSLCompiler defineSupportedShaders
INFO: Supported shader profiles: 
#define v110
#define v120
#define v130
#define v140
#define v150

27 nov. 2013 19:31:59 si.xlab.gaea.core.shaders.BasicGLSLCompiler loadProgram
INFO: Compiling shader: /D:/Documents/GitHub/gaeaplus/out/production/gaeaplus/si/xlab/gaea/core/shaders/data/TerrainNormal.glsl
27 nov. 2013 19:31:59 si.xlab.gaea.core.shaders.BasicGLSLCompiler checkShaderError
INFO: Shader message: WARNING: 0:1: Only GLSL version > 110 allows postfix "F" or "f" for float

27 nov. 2013 19:31:59 si.xlab.gaea.core.shaders.BasicGLSLCompiler checkShaderError
INFO: Shader message: WARNING: 0:1: Only GLSL version > 110 allows postfix "F" or "f" for float

27 nov. 2013 19:31:59 si.xlab.gaea.core.shaders.BasicShaderFactory buildGLSLShader
INFO: Shader loaded: /D:/Documents/GitHub/gaeaplus/out/production/gaeaplus/si/xlab/gaea/core/shaders/data/TerrainNormal.glsl
27 nov. 2013 19:32:03 si.xlab.gaea.core.shaders.BasicGLSLCompiler loadProgram
INFO: Compiling shader: /D:/Documents/GitHub/gaeaplus/out/production/gaeaplus/si/xlab/gaea/core/shaders/data/SurfaceTileShader.glsl
27 nov. 2013 19:32:03 si.xlab.gaea.core.shaders.BasicShaderFactory buildGLSLShader
INFO: Shader loaded: /D:/Documents/GitHub/gaeaplus/out/production/gaeaplus/si/xlab/gaea/core/shaders/data/SurfaceTileShader.glsl
27 nov. 2013 19:32:04 si.xlab.gaea.core.shaders.BasicGLSLCompiler printGLLog
GRAVE: OpenGL error number: 1282 description: invalid operation
27 nov. 2013 19:32:04 si.xlab.gaea.core.shaders.BasicGLSLCompiler loadProgram
INFO: Compiling shader: /D:/Documents/GitHub/gaeaplus/out/production/gaeaplus/si/xlab/gaea/core/shaders/data/SlopeLayer.glsl
27 nov. 2013 19:32:04 si.xlab.gaea.core.shaders.BasicShaderFactory buildGLSLShader
INFO: Shader loaded: /D:/Documents/GitHub/gaeaplus/out/production/gaeaplus/si/xlab/gaea/core/shaders/data/SlopeLayer.glsl
27 nov. 2013 19:32:05 si.xlab.gaea.core.shaders.BasicGLSLCompiler printGLLog
GRAVE: OpenGL error number: 1282 description: invalid operation
27 nov. 2013 19:32:19 si.xlab.gaea.core.shaders.BasicGLSLCompiler loadProgram
INFO: Compiling shader: /D:/Documents/GitHub/gaeaplus/out/production/gaeaplus/si/xlab/gaea/core/shaders/data/TerrainLightingAerialPerspective_1.glsl
27 nov. 2013 19:32:19 si.xlab.gaea.core.shaders.BasicGLSLCompiler checkShaderLinkError
INFO: Shader validation: Validation Error: Samplers of different types point to the same texture unit
Validation Error: Samplers of different types point to the same texture unit
Validation Error: Samplers of different types point to the same texture unit
Validation Error: Samplers of different types point to the same texture unit

27 nov. 2013 19:32:19 si.xlab.gaea.core.shaders.BasicShaderFactory buildGLSLShader
GRAVE: Incomplete BasicShader: /D:/Documents/GitHub/gaeaplus/out/production/gaeaplus/si/xlab/gaea/core/shaders/data/TerrainLightingAerialPerspective_1.glsl
27 nov. 2013 19:32:19 si.xlab.gaea.core.shaders.BasicGLSLCompiler loadProgram
INFO: Compiling shader: /D:/Documents/GitHub/gaeaplus/out/production/gaeaplus/si/xlab/gaea/core/shaders/data/Atmosphere_1.glsl
27 nov. 2013 19:32:19 si.xlab.gaea.core.shaders.BasicGLSLCompiler checkShaderLinkError
INFO: Shader validation: Validation Error: Samplers of different types point to the same texture unit
Validation Error: Samplers of different types point to the same texture unit

27 nov. 2013 19:32:19 si.xlab.gaea.core.shaders.BasicShaderFactory buildGLSLShader
GRAVE: Incomplete BasicShader: /D:/Documents/GitHub/gaeaplus/out/production/gaeaplus/si/xlab/gaea/core/shaders/data/Atmosphere_1.glsl

**Comment by vcucek** [comment] 2013-12-02 14:28
Hello,

I would like to inform you, that we have fixed some problems.

Main improvements are:
1. Improved support for Ati graphic cards. I have fixed some OpenGL code, that was not written strictly by the OpenGL specification. From now on, Gaeaplus should work on Ati graphic cards (all features tested on ATI Radeon HD 5770).
2. Improved overall compatibility and stability.
3. Memory leak in initial loading screen fixed. Because of this memory leak, computer could freeze to death during downloading and preprocessing of elevation data.
4. Improved performance by caching uniform parameters values and removing redundant OpenGL calls.
5. Problem while reading atmosphere resource file fixed.

@ens121: I don't know why you get the second error. I have fixed problem with resource and it work (tested on several machines with jdk 1.6, jdk 1.7 and openjdk 1.7).

@Pheonor: Now it should work. You may still get "Only GLSL version > 110 allows postfix "F" or "f" for float" warning, but i hope that this does not effect program usability. Currently i can not reproduce this warning on any computer available.

Please let me know, if last commit fixes any of your problems.

Regards,
Vito

**Comment by Pheonor** [comment] 2013-12-02 20:38
Great work !

Now, it work perfectly on my computer and the result is pretty cool. Thanks you !

No more error during loading time (except for compatibility warning).

Regards,
Pheo

**Comment by ghost** [comment] 2013-12-02 20:47
Working for me too, thank you.

I did get into a state where the overview, controls, and compass layers were all red. The placenames were also red. The entire map view turned completely red when I showed just the default World Wind Shading.

This is easily repeatable by turning on "Steep Areas" layer, then selecting "Default World Wind" for the Shading. Once this happened, I had to restart UI to get rid of the red.

**Comment by gberginc** [comment] 2013-12-02 21:31
Thanks guys for confirming the resolution and sorry the delay. Since the original report is fixed, I am closing this issue

Thus, @ens121 could you please open a new issue for controls becoming red?

**Closed as completed by gberginc** 2013-12-02 21:31 UTC
Labels: bug

**Comment by clarejor** [comment] 2013-12-03 03:24
The latest code fixed it for me as well. Looks awesome, thanks!
